apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pg2osync.fullname" . }}
  labels:
    {{- include "pg2osync.labels" . | nindent 4 }}
data:
  pg2osync.toml: |
    {{- include "pg2osync.config" . | nindent 4 }}
