{{- if and .Values.secrets (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg2osync.fullname" . }}
  labels:
    {{- include "pg2osync.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
