apiVersion: v2
name: pg2osync
description: Real-time PostgreSQL/MySQL to OpenSearch, Elasticsearch and Meilisearch sync
type: application
version: 1.5.1 # x-release-please-version
appVersion: "1.5.1" # x-release-please-version
home: https://github.com/kennywillbe/pg2osync
sources:
  - https://github.com/kennywillbe/pg2osync
keywords:
  - cdc
  - postgresql
  - mysql
  - opensearch
  - elasticsearch
maintainers:
  - name: pg2osync contributors
