[package]
name = "pg2osync-source"
version = "1.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "PostgreSQL logical-replication source for pg2osync"

[dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow.workspace = true
base64 = "0.23.1"
bytes = "1.12.1"
pg2osync-core = { path = "../core" }
pg2osync-tls = { path = "../tls" }
pgwire-replication.workspace = true
serde_json.workspace = true
thiserror = "2"
tokio = { workspace = true, features = ["signal"] }
tokio-postgres = { workspace = true, features = ["with-serde_json-1"] }
tracing.workspace = true
url = "2.5.8"
tokio-postgres-rustls = "0.14.0"
