[package]
name = "pg2osync-engine"
version = "1.2.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Batching, checkpointing and transform engine for pg2osync"

[dependencies]
serde.workspace = true
pg2osync-core = { path = "../core" }
tokio.workspace = true
tracing.workspace = true
serde_json.workspace = true
sha2 = "0.11.0"
chrono.workspace = true
thiserror.workspace = true
aes-siv = { version = "0.8.0", default-features = false, features = ["alloc"] }
base64 = "0.23.1"
zeroize = { version = "1", default-features = false }

[dev-dependencies]
async-trait.workspace = true
